
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-vie : false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/reservation
    username: sa
    password:
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace